apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: frontend
    
spec:
  containers:
  - name: my-nginx-container
    image: nginx
    # image: dockerjustyna95/test:tagname