apiVersion: apps/v1

kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: backend

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: backend
    spec:
      containers:
      - name: my-nginx-container
        image: dockerjustyna95/k8s-lab2:latest

  replicas: 3

  selector:
    matchLabels:
      type: backend