apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  ports:
  # port na ktorym bedzie udostepnial
    - port: 6379
    # port ktory  redis dziala
      targetPort: 6379 
  selector:
    type: cache

