apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30008
      # port ktory  dzialalal by przy wywolaniu przez yarn start lokalnie
      targetPort: 5000
  selector:
    app: myapp-backend
    type: backend

